### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by gmmkmtgk** [Abhishekkr3003/Auto-Network-Login#1]
Sir we can make crome extension of this program or convert this to software exe file

**Comment by Abhishekkr3003** [comment]
@gmmkmtgk I have added executables for Windows and Linux in the latest release. You can now download it.

**Comment by gmmkmtgk** [comment]
when ever I get time sir I will also make a crome extension for this
Anyways thank you sir never thought of creating this🙌

**Comment by Abhishekkr3003** [comment]
I will be waiting for your PR.
